// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ImiCUNdfZLk-BwLgjd5BrEMqhN7pxeE',
    appId: '1:155872351393:web:d1e1d0fbbdf74bb28a4ce0',
    messagingSenderId: '155872351393',
    projectId: 'database-fd4bc',
    authDomain: 'database-fd4bc.firebaseapp.com',
    storageBucket: 'database-fd4bc.firebasestorage.app',
    measurementId: 'G-YNFYKQDM0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH9_s1F3bE-e0aDCWEt4WzehflbkZdMIo',
    appId: '1:155872351393:android:afea00608664e2108a4ce0',
    messagingSenderId: '155872351393',
    projectId: 'database-fd4bc',
    storageBucket: 'database-fd4bc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ImiCUNdfZLk-BwLgjd5BrEMqhN7pxeE',
    appId: '1:155872351393:web:feb73b207ade7d728a4ce0',
    messagingSenderId: '155872351393',
    projectId: 'database-fd4bc',
    authDomain: 'database-fd4bc.firebaseapp.com',
    storageBucket: 'database-fd4bc.firebasestorage.app',
    measurementId: 'G-LWL02H31B9',
  );
}
